move styles
RobertPashaev/how-to-learn pull request #1
Opened 2023-04-08 20:12 UTC by RobertPashaev

2023-04-08 21:14 UTC, IlyaShorin requested changes
Спасибо за работу, ты большой молодец!
Если чатгпт тебе не помогал, то можешь гордиться собой) (даже если помогал, всё равно можешь гордиться) За этот год ты точно приобрёл необходимые навыки, которых тебе не хватило в прошлый раз. 
продолжай в том же духе, и у тебя получится достичь чего угодно на этом не лёгком пути!

2023-04-08 21:14 UTC, IlyaShorin commented on index.html
> +            Узнать</a
лучше не использовать ::after а использовать что-то попроще например https://pixelplus.ru/studio/stat/html-simvoly-tablitsa-spetssimvolov-v-formate-html/

2023-04-08 21:14 UTC, IlyaShorin commented on index.html
>    <head>
не плохо было бы проверить разметку в онлайн валидаторе, и исправить все Error
Warning по желанию 
https://validator.w3.org/#validate_by_input

2023-04-08 21:14 UTC, IlyaShorin commented on index.html
> +          class="block logo logo_place_header"
лишний класс block
видимо тебя смутило то как написано в брифе.

2023-04-08 21:14 UTC, IlyaShorin commented on styles/style.css
> +  height: 100vh;
это зачем? vh используется крайне крайне редко. обычно используется %, но здесь тебе он не нужен, так как у тебя уже указана МИНИМАЛЬНАЯ и МАКСИМАЛЬНАЯ высота.

2023-04-08 21:14 UTC, IlyaShorin commented on styles/style.css
> +  z-index: 100;
лучше не использовать такие большие цифры, сам потом запутаешься в них. достаточно 0,1,2, как правило больше не бывает. 
ну для модальных окон можно сделать 9999

2023-04-08 21:14 UTC, IlyaShorin commented on index.html
> +            <h3 class="two-columns__brief">Главные проблемы в обучении</h3>
обычно не используется ничего кроме h2, крайне редко где-то будет h3. 
обычно это h1 и h2.

вот например если в пределах одного блока будет заголовок подзаголовок и подподзаголовок тогда наверно можно h3
а у тебя тут есть один заголовок h1 на всю страницу, а дальше всё остальные это подзаголовки этого заголовка.

2023-04-08 21:14 UTC, IlyaShorin commented on styles/style.css
> +  margin-top: 100px;
у тебя у блока который находится над этим есть свойство margin-bottom, они дублируют друг друга. это не нужно.

2023-04-08 21:14 UTC, IlyaShorin commented on styles/style.css
> +  flex-basis: 80%;
это ты придумал, в брифе этого нет :)
там есть width:80%

2023-04-08 21:14 UTC, IlyaShorin commented on styles/style.css
> +  flex-direction: column;
не работает без свойства display:flex
так что тебе это не нужно.

2023-04-08 21:14 UTC, IlyaShorin commented on styles/style.css
> +  margin-top: 30px;
обрати внимание, что у тебя верстка расходится с макетом. 
у тебя первый параграф имеет отступ от верхней границы блока, а по макету должен прилегать вплотную. 
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/63648902/230741597-ae407e6c-df30-482a-ad4c-496a0b547437.png">
<img width="567" alt="image" src="https://user-images.githubusercontent.com/63648902/230741609-b7132db8-330e-41fb-962c-fc38a136a5a7.png">

2023-04-08 21:14 UTC, IlyaShorin commented on styles/style.css
> +  margin-top: 100px;
а здесь этот отступ наложился на отступ в классе .digits
итого общий отступ получился аж 200px

2023-04-08 21:14 UTC, IlyaShorin commented on styles/style.css
> +  height: 790px;
890px

2023-04-08 21:14 UTC, IlyaShorin commented on styles/style.css
> +  position: relative;
а чего не сделать флексом? абсолютного позиционирования лучше избегать.

2023-04-08 21:14 UTC, IlyaShorin commented on styles/style.css
> +  margin-top: 20px;
не обнулил margin

2023-04-08 21:14 UTC, IlyaShorin commented on styles/style.css
> +  margin: 0;
по макету надо задать отступ между текстом и иконкой 10пх

2023-04-24 18:23 UTC, RobertPashaev reviewed
.

2023-04-24 18:27 UTC, closed without merging